---
- name: Create a directory if it does not exist
  become: True
  ansible.builtin.file:
    path: '{{ build_path }}'
    state: directory
    owner: ansible
    mode: '0755'

- name: Copy file with owner and permissions
  template:
    src: 'templates/Dockerfile.j2'
    dest: '{{ build_path }}/Dockerfile'
    mode: '0644'

- name: Build image and with build args
  community.docker.docker_image:
    name: '{{ pfa_custom_image }}'
    build:
      path: '{{ build_path }}/'
      dockerfile: Dockerfile
    source: build

...
